"""create index

Revision ID: 229cce23cc01
Revises: 556f6f1fcd3a
Create Date: 2023-05-08 10:16:57.696797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229cce23cc01'
down_revision = '556f6f1fcd3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trades_delivery_day'), 'trades', ['delivery_day'], unique=False)
    op.create_index(op.f('ix_trades_trader_id'), 'trades', ['trader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trader_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_delivery_day'), table_name='trades')
    # ### end Alembic commands ###
